# Generated by Django 4.1.7 on 2023-03-09 14:28

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='title')),
                ('slug', models.SlugField(allow_unicode=True, max_length=500, unique=True, verbose_name='slug')),
                ('short_description', ckeditor.fields.RichTextField(blank=True, verbose_name='short description')),
                ('description', ckeditor.fields.RichTextField(blank=True, verbose_name='description')),
                ('price', models.PositiveIntegerField(verbose_name='price')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('status', models.CharField(choices=[('ava', 'available'), ('not', 'not_available')], default='ava', max_length=3, verbose_name='status')),
                ('image', models.ImageField(upload_to='covers/', verbose_name='image')),
                ('datetime_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='datetime_created')),
                ('datetime_modified', models.DateTimeField(auto_now=True, verbose_name='datetime_modified')),
                ('category', models.ManyToManyField(related_name='products', to='categories.category', verbose_name='category')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'ordering': ['-datetime_created'],
            },
        ),
    ]
